apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: graf-data-dir-pvc
  namespace: monitoring
  labels:
    app: grafana

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi